# Generated by Django 5.0.1 on 2024-02-24 02:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("estoque", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Estoque",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hemocentro", models.CharField(max_length=100)),
                ("tipo_sanguineo", models.CharField(max_length=5)),
                ("estoque_atual_A_positivo", models.IntegerField(default=0)),
                ("estoque_minimo_A_positivo", models.IntegerField(default=0)),
                ("estoque_atual_A_negativo", models.IntegerField(default=0)),
                ("estoque_minimo_A_negativo", models.IntegerField(default=0)),
                ("estoque_atual_B_positivo", models.IntegerField(default=0)),
                ("estoque_minimo_B_positivo", models.IntegerField(default=0)),
                ("estoque_atual_B_negativo", models.IntegerField(default=0)),
                ("estoque_minimo_B_negativo", models.IntegerField(default=0)),
                ("estoque_atual_AB_positivo", models.IntegerField(default=0)),
                ("estoque_minimo_AB_positivo", models.IntegerField(default=0)),
                ("estoque_atual_AB_negativo", models.IntegerField(default=0)),
                ("estoque_minimo_AB_negativo", models.IntegerField(default=0)),
                ("estoque_atual_O_positivo", models.IntegerField(default=0)),
                ("estoque_minimo_O_positivo", models.IntegerField(default=0)),
                ("estoque_atual_O_negativo", models.IntegerField(default=0)),
                ("estoque_minimo_O_negativo", models.IntegerField(default=0)),
            ],
        ),
    ]
