# Generated by Django 5.0.1 on 2024-02-24 02:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("estoque", "0003_delete_estoque_remove_estoquesangue_estoque_atual_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="estoquesangue",
            name="tipo_sanguineo",
        ),
    ]
