# Generated by Django 5.0.1 on 2024-02-24 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("estoque", "0004_remove_estoquesangue_tipo_sanguineo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="estoquesangue",
            name="hemocentro",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="estoque.hemocentro"
            ),
        ),
    ]
