# Generated by Django 5.0.1 on 2024-02-24 15:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("estoque", "0005_alter_estoquesangue_hemocentro"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="estoquesangue",
            table="EstoqueSangue",
        ),
    ]
