# Generated by Django 5.0.1 on 2024-02-24 15:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("estoque", "0006_alter_estoquesangue_table"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="estoquesangue",
            options={"verbose_name_plural": "EstoqueSangue"},
        ),
        migrations.AlterModelTable(
            name="estoquesangue",
            table=None,
        ),
    ]
